name: Game Issue
description: 'Choose this if you''re having trouble with a game'
title: "[Game Issue] "
body:
  - type: input
    id: game_name
    attributes:
      label: Game Name
      placeholder: "ex. 20XX"
    validations:
      required: true
  - type: textarea
    id: current_state
    attributes:
      label: What is happening?
      placeholder: 'ex. "The game doesn''t start"; "graphics are displayed wrong"... Please be detailed here'
    validations:
      required: true
  - type: textarea
    id: game_log
    attributes:
      label: Game log
      description: 'Upload the game''s log here, ideally with timestamps so we can see what''s happening when'
    validations:
      required: true
  - type: textarea
    id: system_info
    attributes:
      label: System information
      description: 'Run `inxi -SCGm` and copy the output into here'
    validations:
      required: true
  - type: input
    id: wine_version
    attributes:
      label: Wine Version
      description: What Wine version was used to test the game?
    validations:
      required: true
  - type: checkboxes
    id: dxvk
    attributes:
      label: Common issues
      options:
        - label: I have verified that this issue is not resolved by installing DXVK/vkd3d-proton
          required: true
        - label: I have verified that this issue is not resolved by enabling virtual desktop
          required: true
        - label: I have verified that this issue is also occurring in a clean Wineprefix (meaning a prefix that has only this one game installed)
          required: true
